### ISSUE TITLE
when you click "Chapter 2: Binary recursive partitioning with CART",you will get "chap-intro.R",it is for the chap1

### ISSUE THREAD

**Issue by A-Pai** [bgreenwell/treebook#9]
https://bgreenwell.github.io/treebook/rscripts.html
when you click "Chapter 2: Binary recursive partitioning with CART",you will get "chap-intro.R",it is for the chap1

**Comment by bgreenwell** [comment]
Ahh, thanks @A-Pai, should be fixed now!

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  Li Gang
